config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root 'devise/sessions#new'
  end

  resources :posts
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :users, only: [:show, :index]
  resources :comments, only: [:create]
  resources :likes, only: [:create, :destroy]
  resources :friend_requests, only: [:index, :create, :destroy]
  resources :friendships, only: [:create]
  delete 'friendships', to: 'friendships#destroy'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: %i[user_id]
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.build(like_params)

    if @like.save
      flash.notice = 'You liked that post'
    else
      flash.alert = 'You\'ve already liked that'
    end
    redirect_to posts_path
  end

  def destroy
    @like = Like.find(params[:id])

    @like.destroy
    flash.notice = 'You unliked that post'
    redirect_to posts_path
  end

  private

  def like_params
    params.permit(:post_id)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like_button.html.erb
<% like = current_user.liked_posts.include?(post) ? Like.find_by(post_id: post.id, user_id: current_user.id) : nil %>

<div class='post-buttons-container'>
  <% if like %>
    <%= link_to like_path(like), method: :delete, class: 'like-button' do %>
      <span class='like-text'>Unlike</span>
    <% end %>
  <% else %>
    <%= link_to likes_path(post_id: post.id), method: :post, class: 'like-button' do %>
      <i class='like-icon'></i> <span class='like-button-text'>Like</span>
    <% end %>
  <% end %>

  <a href='#' class='comment-button'>
    <i class='comment-icon'></i><span class='comment-button-text'>Comment</span>
  </a>
</div>

app/views/likes/_likes.html.erb
<% post.likes.each do |like| %>
  <%= like.user.first_name %> liked this
<% end %>