config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root 'devise/sessions#new'
  end

  resources :posts
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :users, only: [:show, :index]
  resources :comments, only: [:create]
  resources :likes, only: [:create, :destroy]
  resources :friend_requests, only: [:index, :create, :destroy]
  resources :friendships, only: [:create]
  delete 'friendships', to: 'friendships#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :profile_picture, ProfilePictureUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Make user omniauthable
  devise :omniauthable, omniauth_providers: %i[facebook]
  
  # User Profile Picture Validation
  validates_integrity_of :profile_picture
  validates_processing_of :profile_picture

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, class_name: 'Post', source: 'post'
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :incoming_friend_requests, class_name: 'FriendRequest', foreign_key: 'recipient_id', dependent: :destroy
  has_many :outgoing_friend_requests, class_name: 'FriendRequest', foreign_key: 'from_id', dependent: :destroy

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.name.split[0]   # assuming the user model has a name
      user.last_name = auth.info.name.split[1]
      user.profile_picture = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  private

  def avatar_size_validation
    errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :facebook

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user 
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    flash.notice = 'Sign in failed. Please try again.'
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    # UserMailer.with(user: resource).welcome_email.deliver unless resource.invalid?
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def after_update_path_for(resource)
    user_path(resource)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    friend_ids = current_user.friends.pluck(:id) << current_user.id
    friend_or_pending_ids = friend_ids + current_user.outgoing_friend_requests.pluck(:recipient_id)
    @users = User.where.not(id: friend_or_pending_ids)
  end

  def show
    @user = User.includes(:posts).find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friend.html.erb
<%= link_to user_path(friend), class:(request ? 'friend-trigger trigger-flex' : 'friend-trigger') do %>
  <div class='friend'>
    <%= image_tag friend.profile_picture.thumb.url, class:'profile-img' %>
    <span class='requester-name'><%= friend.first_name + ' ' + friend.last_name %></span>
    <% if request %>
      <div class='buttons'>
        <%= link_to 'Confirm', friendships_path(recipient_id: friend.id, request_id: id), method: :post, class:'button button-confirm' %>
        <%= link_to 'Ignore', friend_request_path(id: id), method: :delete, class:'button button-ignore' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class='container center'>
  <h1>Find Friends</h1>

  <div class='col-2'>
    <% @users.each do |user| %>
      <%= link_to user_path(user), class:'friend-trigger' do %>
        <div class='friend'>
          <%= image_tag user.profile_picture.thumb.url, class:'profile-img' %>
          <%= user.first_name + ' ' + user.last_name %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% unless @user.profile_picture.nil? %>
  <div class='profile-picture-wrapper'>
    <%= image_tag @user.profile_picture.profile.url,class:'profile-picture' %>
  </div>
<% end %>

<div class='profile-info'>
  <h2 class=''><%= @user.first_name %> <%= @user.last_name %></h2>

  <% if @user.birthday %>
    <p>Birthday: <%= @user.birthday %></p>
  <% end %>

  <% if @user.location && !@user.location.empty? %>
    <p>Lives in: <%= @user.location %></p>
  <% end %>

  <% if current_user == @user %>
    <p><%= link_to 'Edit Profile', edit_user_registration_path(current_user), class:'button' %></p>
  <% elsif @user.incoming_friend_requests.pluck(:from_id).include?(current_user.id) %>
    <p>Friend Request Sent</p>
  <% elsif current_user.friends.include?(@user) %>
    <p>You are friends with <%= @user.first_name %></p>
    <%= link_to 'Unfriend', friendships_path(user_id: current_user.id, friend_id: @user.id), method: :delete, class:'button' %>
  <% elsif @user.outgoing_friend_requests.pluck(:recipient_id).include?(current_user.id) %>
    <p><%= link_to @user.first_name + ' wants to be your friend', friend_requests_path %></p>
  <% else %>
    <p><%= link_to 'Send Friend Request', friend_requests_path(recipient_id: @user.id), method: :post, class:'button' %></p>
  <% end %>
</div>

<div class='container'>
  <h3>Posts</h3>

  <% @user.posts.order(created_at: :desc).each do |post| %>
    <div class='post'>
      <%= render partial: 'posts/post', locals: {post: post} %>
    </div>
  <% end %>
</div>

<div class='container'>
  <h3>Friends</h3>

  <div class='col-2'>
    <% @user.friends.each do |friend| %>
      <%= render partial: 'friend', locals: {request:false, friend: friend} %>
    <% end %>
  </div>
</div>