config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root 'devise/sessions#new'
  end

  resources :posts
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :users, only: [:show, :index]
  resources :comments, only: [:create]
  resources :likes, only: [:create, :destroy]
  resources :friend_requests, only: [:index, :create, :destroy]
  resources :friendships, only: [:create]
  delete 'friendships', to: 'friendships#destroy'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :set_comment, only: [:show, :index]
  before_action :verify_user, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    friend_ids = current_user.friends.pluck(:id) << current_user.id
    @posts = Post.includes(:user).where(user_id: friend_ids).order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.includes(:comments, :likes).find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_comment
      @comment = Comment.new
    end

    def verify_user
      unless current_user == @post.user
        flash.notice = 'You can\'t edit another user\'s posts'
        redirect_back(fallback_location: posts_path)
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.erb
<% post.comments.each do |comment| %>
  <div class='comment'>
    <a href=<%= user_path(comment.user) %>><%= image_tag comment.user.profile_picture.thumb.url, class:'comment-pic' %></a>
    <div class='comment-main'>
      <p class='comment-author'>
        <a href=<%= user_path(comment.user) %> ><%= comment.user.first_name %> <%= comment.user.last_name %></a>
      </p>
      <%= comment.content %><br/>
    </div>
  </div>

  <p class='timestamp'><%= time_ago_in_words(comment.created_at)%> ago</p>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.text_area :content, class:'post-area' %>
  </div>

  <div class="actions">
    <%= form.submit 'Post', class:'button center' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class='poster-info'>
  <a href=<%= user_path(post.user) %>>
    <%= image_tag post.user.profile_picture.thumb.url, class:'profile-img' %>
  </a>
  <ul class='text-info'>
    <li><%= post.user.first_name %> <%= post.user.last_name %></li>
    <li><%= time_ago_in_words(post.created_at) %> ago</li>
  </ul>

  <%= link_to 'Show Post', post_path(post), class:'post-link nav-link' %>
</div>

<p class='content'>
  <%= post.content %>
</p>

<div class='post-info'>
  <p>
    <%= pluralize(post.likes.count, 'like') %> 
  </p>
  <p>
    <%= pluralize(post.comments.count, 'comment') %> 
  </p>
</div>

app/views/posts/edit.html.erb
<div class='container center'>
  <h1>Edit Post</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Back', @post, class:'nav-link' %>
</div>

app/views/posts/index.html.erb
<%= link_to 'New Post', new_post_path, class:'button new-post' %>

<div class='container'>
  <% @posts.each do |post| %>
    <div class='post'>
      <%= render partial: 'posts/post', locals: {post: post} %>
      <%# <%= render partial: 'likes/likes', locals: {post: post} %>

      <div class='horizontal-divider full-width'></div>
      
      <%= render partial: 'likes/like_button', locals: {post: post} %>

      <div class='horizontal-divider full-width'></div>

      <%= render partial: 'comments/form', locals: {post: post} %>
      <%= render partial: 'posts/comments', locals: {post: post} %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class='container center'>
  <h1>New Post</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Back', posts_path, class:'nav-link' %>
</div>

app/views/posts/show.html.erb
<div class='container'>
  <div class='post'>
    <%= render partial: 'posts/post', locals: {post: @post} %>

    <div class='horizontal-divider full-width'></div>
      
      <%= render partial: 'likes/like_button', locals: {post: @post} %>

      <div class='horizontal-divider full-width'></div>

    <div class='comments'>
      <%= render partial: 'posts/comments', locals: {post: @post} %>
    </div>

    <% if current_user == @post.user %>
      <%= link_to 'Edit', edit_post_path(@post), class:'button button-small' %> 
    <% end %>
    <%= link_to 'Back', posts_path, class:'button button-small' %>
  </div>
</div>