config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root 'devise/sessions#new'
  end

  resources :posts
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :users, only: [:show, :index]
  resources :comments, only: [:create]
  resources :likes, only: [:create, :destroy]
  resources :friend_requests, only: [:index, :create, :destroy]
  resources :friendships, only: [:create]
  delete 'friendships', to: 'friendships#destroy'
end

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <ul class='nav'>
    <li><%= link_to 'Home', posts_path, class:'nav-item' %></li>
    <li><%= link_to 'Requests', friend_requests_path, class:'nav-item' %></li>
    <li><%= link_to 'Find Friends', users_path, class:'nav-item' %></li>
    <li><%= link_to 'My Profile', user_path(current_user), class:'nav-item' %></li>
    <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:'nav-item' %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFacebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
  </head>

  <body>
    <%= render 'layouts/navbar' unless @disable_nav %>

    <div class='content-container'>
      <% flash.each do |key, msg| %>
        <p class=<%=key.to_s%>>
          <%= msg %>
        </p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>